//this is a working schema for the digital relationships of the database
//it is meant to be used with dbdiagram.io
Table artist {
  id int [primary key]
  name string

}

Table comic {
  id int [primary key]
  artist_id int [not null]
  comic_name string
  tag int

}

Table comic_page{
  id int [primary key]
  parent_comic_id int [not null]
  img varchar //path to the image
  page int
}

Table gallery_image {
  id int [primary key]
  artist_id int [not null]
  img varchar 
  tag int
  
}
Table comic_tags{
  id int [primary key]
  applied_tags int [not null]
}

Table image_tags{
  id int [primary key]
  applied_tags int [not null]
}

Table tag {
  id int [primary key]
  name varchar [not null]
}

Ref: comic.artist_id ?> artist.id

Ref: gallery_image.artist_id ?<> artist.id

Ref: comic_page.parent_comic_id > comic.id

Ref: comic_tags.applied_tags <> tag.id

Ref: comic_tags.id - comic.tag

Ref: image_tags.applied_tags <> tag.id

Ref: image_tags.id - gallery_image.tag
