//this is a working schema for the digital relationships of the database

Table artist {
  id int [primary key]
  name string

}

Table comic {
  id int [primary key]
  artist_id int [not null]
  comic_name string
  tag int

}

Table comic_page{
  id int [primary key]
  parent_comic_id int [not null]
  img image
  page int
}

Table gallery {
  id int [primary key]
  img image
  tag varchar
  
}

Table tag {
  id int [primary key]
  name varchar [not null]
}

Ref: comic.artist_id > artist.id

Ref: gallery.id - artist.id

Ref: comic_page.parent_comic_id > comic.id

Ref: tag.name ?<> gallery.tag

Ref: tag.name ?<> comic.tag
